global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:3000"]
  - job_name: "service-a"
    static_configs:
      - targets: ["service-a:4001"]
  - job_name: "service-b"
    static_configs:
      - targets: ["service-b:4002"]
  - job_name: "service-c"
    static_configs:
      - targets: ["service-c:4003"]
  - job_name: "service-d"
    static_configs:
      - targets: ["service-d:4004"]
  - job_name: "service-e"
    static_configs:
      - targets: ["service-e:4005"]
